### ISSUE TITLE
Feature discussion and planning

### ISSUE THREAD

**Issue by abh80** [abh80/smart-edge#4]
Users can ask for features to be implemented and give suggestion.

> For bugs kindly open a new issue

**Tasks :-**
- [x] Implement Notifications suggested in #1
- [x] Add auto updater
- [x] Add customization such as custom height, position, width

**Comment by mukeshwebs** [comment]
waiting for the update of notifications feature😍

**Comment by abdelmohcen** [comment]
waiting for the notification update.

**Comment by abh80** [comment]
Yes i am almost there expecting to be done by tomorrow, I have to rewrite some stuffs

**Comment by abh80** [comment]
@mukeshwebs @abdelmohcen how about the feature that when media app is open the island remains closed but when in background open the island like in apple?

**Comment by mukeshwebs** [comment]
I would highly advice to keep the dynamic island activate even when user is on the music player screen. the reason is user quickly get to know that their music is also playing and can be controlled from dynamic island. 
keep the dynamic island on the each screen don't hide.
waiting for the update of notification feature. 
after all the features completion I will do the splash screen, instructions screen and few more things...

**Comment by abdelmohcen** [comment]
> I would highly advice to keep the dynamic island activate even when user is on the music player screen. the reason is user quickly get to know that their music is also playing and can be controlled from dynamic island. keep the dynamic island on the each screen don't hide. waiting for the update of notification feature. after all the features completion I will do the splash screen, instructions screen and few more things...

i'm with you in this one keep the dynamic island active and show it all the time + try to a customization setting for height and width

**Comment by mukeshwebs** [comment]
Right customisation for height and width and positioning on different
places in screen is also recommended.

**Comment by abh80** [comment]
Alright I have considered your points.

**Comment by mukeshwebs** [comment]
you try adding the height, width and positioning of dynamic island
for reference i have added the image
![image](https://user-images.githubusercontent.com/53649320/193460883-f45ccdc4-a1ab-43eb-bad4-80007550dd2f.png)

**Comment by abh80** [comment]
Please use #15 for posting features or idea.

**Comment by mukeshwebs** [comment]
#15 
customisation for height and width and positioning on different
places in screen is required.
